from stellar_sdk import Asset


XLM = Asset.native()

YXLM_CODE = 'yXLM'
YXLM_ISSUER = 'GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55'
YXLM = Asset(YXLM_CODE, YXLM_ISSUER)

AQUA_CODE = 'AQUA'
AQUA_ISSUER = 'GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA'
AQUA = Asset(AQUA_CODE, AQUA_ISSUER)
